#!/usr/bin/env python3
"""Generate GitHub Wiki markdown pages from the repository documentation."""

from __future__ import annotations

import argparse
import os
import re
import shutil
from dataclasses import dataclass
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = REPO_ROOT / "docs" / "wiki"
DEFAULT_REPO_URL = "https://github.com/mattilaa/mlang"
DEMO_INDEX_SOURCE = Path("docs/demos.md")
GENERATED_NOTICE = (
    "<!-- Generated by scripts/generate_github_wiki.py. "
    "Update the source documentation and rerun the script. "
    "The generator adds wiki links and code-fence languages. -->\n\n"
)
GITHUB_FENCE_LANGUAGE_ALIASES = {
    "mla": "rust",
    "mlang": "rust",
}


@dataclass(frozen=True)
class Page:
    source: Path
    title: str
    wiki_name: str
    group: str


STDLIB_MODULE_DOCS: list[tuple[str, str]] = [
    ("std::algorithm::genetic", "std_algorithm_genetic.md"),
    ("std::algorithm::numeric", "std_algorithm_numeric.md"),
    ("std::algorithm::order", "std_algorithm_order.md"),
    ("std::algorithm::ranges", "std_algorithm_ranges.md"),
    ("std::argparser", "std_argparser.md"),
    ("std::array", "std_array.md"),
    ("std::audio", "std_audio.md"),
    ("std::bench", "std_bench.md"),
    ("std::bits", "std_bits.md"),
    ("std::bitset", "std_bitset.md"),
    ("std::bytes", "std_bytes.md"),
    ("std::chat", "std_chat.md"),
    ("std::compiler", "std_compiler.md"),
    ("std::date", "std_date.md"),
    ("std::env", "std_env.md"),
    ("std::esc", "std_esc.md"),
    ("std::event_loop", "std_event_loop.md"),
    ("std::exceptions", "std_exceptions.md"),
    ("std::fs", "std_fs.md"),
    ("std::gps", "std_gps.md"),
    ("std::hash", "std_hash.md"),
    ("std::image", "std_image.md"),
    ("std::io", "std_io.md"),
    ("std::ipc", "std_ipc.md"),
    ("std::json", "std_json.md"),
    ("std::jsonrpc", "std_jsonrpc.md"),
    ("std::limits", "std_limits.md"),
    ("std::log", "std_log.md"),
    ("std::math", "std_math.md"),
    ("std::net", "std_net.md"),
    ("std::platform", "std_platform.md"),
    ("std::printf", "std_printf.md"),
    ("std::process", "std_process.md"),
    ("std::protocol", "std_protocol.md"),
    ("std::rand", "std_rand.md"),
    ("std::regex", "std_regex.md"),
    ("std::sed", "std_sed.md"),
    ("std::serde", "std_serde.md"),
    ("std::simd", "std_simd.md"),
    ("std::span", "std_span.md"),
    ("std::strbuf", "std_strbuf.md"),
    ("std::sync", "std_sync.md"),
    ("std::term", "std_term.md"),
    ("std::testing", "std_testing.md"),
    ("std::thread", "std_thread.md"),
    ("std::time", "std_time.md"),
    ("std::timer", "std_timer.md"),
    ("std::unordered", "std_unordered.md"),
    ("std::vec", "std_vec.md"),
]

MATH_DSP_MODULES = {
    "std::algorithm::numeric",
    "std::audio",
    "std::math",
    "std::rand",
    "std::simd",
}


def stdlib_module_wiki_name(module: str) -> str:
    suffix = module.removeprefix("std::").replace("::", "-").replace("_", "-")
    return "Stdlib-" + "-".join(part.capitalize() for part in suffix.split("-"))


def old_stdlib_module_wiki_name(module: str) -> str:
    return "Stdlib-" + module.replace("std::", "std-").replace("::", "-")


PAGES: list[Page] = [
    Page(Path("docs/README.md"), "MLang Documentation", "Home", "Start Here"),
    Page(Path("docs/new_features.md"), "New Features Guide", "New-Features", "Start Here"),
    Page(Path("README.md"), "Project README", "Project-README", "Start Here"),
    Page(Path("docs/compiler_diagnostics.md"), "Compiler Diagnostics", "Compiler-Diagnostics", "Language"),
    Page(Path("docs/language_attributes.md"), "Language Attributes", "Language-Attributes", "Language"),
    Page(Path("docs/language_builtins.md"), "Language Built-ins", "Language-Built-ins", "Language"),
    Page(Path("docs/language_syntax.md"), "Language Syntax", "Language-Syntax", "Language"),
    Page(Path("docs/quick_guide.md"), "Quick Guide", "Quick-Guide", "Language"),
    Page(Path("docs/examples.md"), "Examples", "Examples", "Examples"),
    Page(DEMO_INDEX_SOURCE, "Directory Demos", "Demos", "Demos"),
    Page(Path("examples/qemu_x86_bootloader/README.md"), "MLang QEMU x86 Bootloader Example", "QEMU-x86-Bootloader-Example", "Demos"),
    Page(Path("examples/qemu_aarch64_bootloader/README.md"), "MLang QEMU AArch64 Boot Example", "QEMU-AArch64-Boot-Example", "Demos"),
    Page(Path("docs/uml_ui_generator.md"), "UML UI Generator", "UML-UI-Generator", "Demos"),
    Page(Path("examples/uml_ui_generator/README.md"), "UML UI Generator Example", "UML-UI-Generator-Example", "Demos"),
    Page(Path("docs/stdlib_changes_2026-03-13.md"), "Stdlib Changes 2026-03-13", "Stdlib-Changes-2026-03-13", "Standard Library"),
    Page(Path("docs/stdlib_misc_modules.md"), "Stdlib Misc Modules", "Stdlib-Misc-Modules", "Standard Library"),
    Page(Path("docs/stdlib_mlang_api.md"), "Stdlib Module API", "Stdlib-Module-API", "Standard Library"),
    Page(Path("stdlib/README.md"), "Stdlib README", "Stdlib-README", "Standard Library"),
    Page(Path("docs/dsp/index.md"), "DSP Library", "DSP", "DSP Library"),
    Page(Path("docs/dsp/filter.md"), "dsp::filter", "DSP-Filter", "DSP Library"),
    Page(Path("docs/dsp/convolution.md"), "dsp::convolution", "DSP-Convolution", "DSP Library"),
    Page(Path("docs/dsp/fft.md"), "dsp::fft", "DSP-FFT", "DSP Library"),
    Page(Path("docs/dsp/limiter.md"), "dsp::limiter", "DSP-Limiter", "DSP Library"),
    Page(Path("docs/dsp/reverb.md"), "dsp::reverb", "DSP-Reverb", "DSP Library"),
    Page(Path("docs/dsp/reverb2.md"), "dsp::reverb2", "DSP-Reverb2", "DSP Library"),
] + [
    Page(
        Path("docs/stdlib") / filename,
        module,
        stdlib_module_wiki_name(module),
        "Math and Audio" if module in MATH_DSP_MODULES else "Stdlib Modules",
    )
    for module, filename in STDLIB_MODULE_DOCS
] + [
    Page(Path("bootstrap/README.md"), "Bootstrap", "Bootstrap", "Tooling"),
    Page(Path("tools/mlangpkg/README.md"), "mlangpkg", "Mlangpkg", "Tooling"),
    Page(Path("docs/package_manager.md"), "Package Manager", "Package-Manager", "Tooling"),
    Page(Path("docs/registry_protocol.md"), "Registry Protocol v1", "Registry-Protocol", "Tooling"),
    Page(Path("tests/README.md"), "Tests", "Tests", "Tooling"),
]

MANPAGES: list[tuple[Path, str]] = [
    (Path("docs/man/mlang.1"), "mlang"),
    (Path("docs/man/mlang-frontend.1"), "mlang-frontend"),
    (Path("docs/man/mlang-frontend-mla.1"), "mlang-frontend-mla"),
    (Path("docs/man/mlang-format.1"), "mlang-format"),
    (Path("docs/man/mlang-pkg.1"), "mlang-pkg"),
    (Path("docs/man/mlangd.1"), "mlangd"),
    (Path("docs/man/mlangd-mla.1"), "mlangd-mla"),
]

LANGUAGE_TOKENS = {
    "fn",
    "let",
    "var",
    "if",
    "else",
    "while",
    "for",
    "return",
    "struct",
    "enum",
    "impl",
    "trait",
    "match",
    "switch",
    "case",
    "mod",
    "use",
    "extern",
    "cexpr",
    "alias",
    "static_assert!",
    "sizeof",
    "bit",
    "bool",
    "void",
    "i8",
    "i16",
    "i32",
    "i64",
    "u8",
    "u16",
    "u32",
    "u64",
    "f32",
    "f64",
    "str8",
    "str16",
    "string",
    "ptr",
    "map",
    "list",
    "list<T>",
    "list<i32>",
    "list<i64>",
    "list<bool>",
    "list<str8>",
    "span",
    "span<T>",
    "option",
    "option<T>",
    "result",
    "result<T, E>",
    "Self",
    "dyn",
}

STDLIB_TYPE_TOKENS = {
    "Vec",
    "Vec<T>",
    "span",
    "Span",
    "Span<T>",
    "span<T>",
    "HashMap",
    "BitSet",
}

STDLIB_MODULE_LINKS = {
    module: stdlib_module_wiki_name(module)
    for module, _filename in STDLIB_MODULE_DOCS
}

STDLIB_TYPE_LINKS = {
    "Vec": STDLIB_MODULE_LINKS["std::vec"],
    "Vec<T>": STDLIB_MODULE_LINKS["std::vec"],
    "span": STDLIB_MODULE_LINKS["std::span"],
    "Span": STDLIB_MODULE_LINKS["std::span"],
    "Span<T>": STDLIB_MODULE_LINKS["std::span"],
    "span<T>": STDLIB_MODULE_LINKS["std::span"],
    "HashMap": STDLIB_MODULE_LINKS["std::unordered"],
    "BitSet": STDLIB_MODULE_LINKS["std::bitset"],
}

STDLIB_MODULES = {
    "std::algorithm::genetic",
    "std::algorithm::numeric",
    "std::algorithm::order",
    "std::algorithm::ranges",
    "std::argparser",
    "std::array",
    "std::audio",
    "std::bench",
    "std::bits",
    "std::bitset",
    "std::bytes",
    "std::chat",
    "std::compiler",
    "std::date",
    "std::env",
    "std::esc",
    "std::event_loop",
    "std::exceptions",
    "std::fs",
    "std::gps",
    "std::hash",
    "std::image",
    "std::io",
    "std::ipc",
    "std::json",
    "std::jsonrpc",
    "std::math",
    "std::net",
    "std::path",
    "std::platform",
    "std::printf",
    "std::process",
    "std::protocol",
    "std::rand",
    "std::regex",
    "std::sed",
    "std::serde",
    "std::simd",
    "std::span",
    "std::ssl",
    "std::strbuf",
    "std::sync",
    "std::term",
    "std::testing",
    "std::thread",
    "std::time",
    "std::timer",
    "std::unordered",
    "std::vec",
}


def wiki_anchor(text: str) -> str:
    anchor = text.strip().lower()
    anchor = re.sub(r"<[^>]+>", "", anchor)
    anchor = re.sub(r"`", "", anchor)
    anchor = re.sub(r"[^a-z0-9 -]", "", anchor)
    anchor = re.sub(r"\s+", "-", anchor)
    anchor = re.sub(r"-+", "-", anchor).strip("-")
    return anchor


def stdlib_module_link(token: str) -> str | None:
    match = re.match(r"^(std::[A-Za-z_][A-Za-z0-9_:]*)", token)
    if not match:
        return None
    full_name = match.group(1)
    parts = full_name.split("::")
    candidates = ["::".join(parts[:count]) for count in range(len(parts), 1, -1)]
    module = next((candidate for candidate in candidates if candidate in STDLIB_MODULES), None)
    if module is None and len(parts) >= 2:
        module = "::".join(parts[:2])
    if module in STDLIB_MODULE_LINKS:
        return STDLIB_MODULE_LINKS[module]
    return "Stdlib-Module-API"


def inline_code_link(token: str) -> str | None:
    if token == "dsp" or token.startswith("dsp::"):
        if token.startswith("dsp::filter"):
            return "DSP-Filter"
        if token.startswith("dsp::convolution"):
            return "DSP-Convolution"
        if token.startswith("dsp::fft"):
            return "DSP-FFT"
        if token.startswith("dsp::limiter"):
            return "DSP-Limiter"
        if token.startswith("dsp::reverb2"):
            return "DSP-Reverb2"
        if token.startswith("dsp::reverb"):
            return "DSP-Reverb"
        return "DSP"
    module_link = stdlib_module_link(token)
    if module_link:
        return module_link
    if token in STDLIB_TYPE_TOKENS:
        return STDLIB_TYPE_LINKS[token]
    if token in LANGUAGE_TOKENS:
        return "Quick-Guide#types" if re.search(r"[0-9]|str|bool|list|map|option|result|Self|dyn|ptr|bit|void|string", token) else "Language-Syntax"
    return None


def slugify_wiki_name(name: str) -> str:
    stem = Path(name).stem
    stem = stem.replace("_", "-").replace(" ", "-")
    stem = re.sub(r"[^A-Za-z0-9.-]+", "-", stem)
    stem = re.sub(r"-+", "-", stem).strip("-")
    return stem or "Page"


def build_source_map(pages: list[Page]) -> dict[Path, str]:
    mapping: dict[Path, str] = {}
    for page in pages:
        mapping[page.source] = page.wiki_name
        mapping[page.source.resolve()] = page.wiki_name
    return mapping


def wiki_link_for(target: str, current_source: Path, source_map: dict[Path, str], repo_url: str) -> str:
    if re.match(r"^[a-zA-Z][a-zA-Z0-9+.-]*:", target):
        return target
    if target.startswith("#"):
        return target

    path_part, hash_part = (target.split("#", 1) + [""])[:2] if "#" in target else (target, "")
    if not path_part:
        return target

    candidate = (current_source.parent / path_part).resolve()
    wiki_name = source_map.get(candidate)
    if wiki_name:
        return f"{wiki_name}{'#' + hash_part if hash_part else ''}"

    repo_relative = os.path.normpath(str((current_source.parent / path_part).as_posix()))
    if repo_relative.startswith("../"):
        repo_relative = repo_relative.lstrip("./")
        while repo_relative.startswith("../"):
            repo_relative = repo_relative[3:]
    return f"{repo_url}/blob/main/{repo_relative}{'#' + hash_part if hash_part else ''}"


def rewrite_markdown_links(text: str, current_source: Path, source_map: dict[Path, str], repo_url: str) -> str:
    def replace_inline(match: re.Match[str]) -> str:
        label = match.group(1)
        target = match.group(2).strip()
        if target.startswith("<") and target.endswith(">"):
            target = target[1:-1]
        return f"[{label}]({wiki_link_for(target, current_source, source_map, repo_url)})"

    text = re.sub(r"(?<!!)\[([^\]]+)\]\(([^)]+)\)", replace_inline, text)

    def replace_reference(match: re.Match[str]) -> str:
        label = match.group(1)
        target = match.group(2).strip()
        return f"[{label}]: {wiki_link_for(target, current_source, source_map, repo_url)}"

    return re.sub(r"^\[([^\]]+)\]:\s*(\S+)\s*$", replace_reference, text, flags=re.MULTILINE)


def infer_fence_language(code_lines: list[str], page: Page) -> str:
    sample = "\n".join(line for line in code_lines if line.strip())[:2000]
    stripped = sample.lstrip()
    if not stripped:
        return ""
    if re.search(r"\b(fn|let|var|struct|enum|impl|mod|use|extern)\b", sample):
        return "rust"
    if re.search(r"\b(mlang|cmake|git|python3|brew|sudo|export|open|cd|cp|mkdir|chmod)\b", sample):
        return "sh"
    if re.search(r"^\s*(\[.+\]|[A-Za-z0-9_.-]+\s*=)", sample, flags=re.MULTILINE):
        return "toml"
    if page.source.suffix == ".md" and "README" in page.source.name and "test" in str(page.source).lower():
        return "text"
    return "text"


def github_fence_language(language: str) -> str:
    language = language.strip()
    if not language:
        return language
    return GITHUB_FENCE_LANGUAGE_ALIASES.get(language.lower(), language)


def add_missing_fence_languages(text: str, page: Page) -> str:
    lines = text.splitlines()
    output: list[str] = []
    in_fence = False
    fence_start_index = -1
    fence_code_lines: list[str] = []

    for line in lines:
        match = re.match(r"^```([^`]*)\s*$", line)
        if match:
            if not in_fence:
                in_fence = True
                fence_start_index = len(output)
                fence_code_lines = []
                language = github_fence_language(match.group(1))
                output.append(f"```{language}" if language else "```")
                continue

            if output[fence_start_index] == "```":
                language = infer_fence_language(fence_code_lines, page)
                if language:
                    output[fence_start_index] = f"```{language}"
            in_fence = False
            output.append(line)
            continue

        if in_fence:
            fence_code_lines.append(line)
        output.append(line)

    return "\n".join(output) + ("\n" if text.endswith("\n") else "")


def convert_doxygen_heading_ids(text: str) -> str:
    def replace(match: re.Match[str]) -> str:
        prefix = match.group(1)
        title = match.group(2).rstrip()
        anchor = match.group(3)
        return f'<a id="{anchor}"></a>\n\n{prefix}{title}'

    return re.sub(r"^(#{1,6}\s+)(.*?)\s+\{#([A-Za-z0-9_-]+)\}\s*$", replace, text, flags=re.MULTILINE)


def link_inline_code_tokens(text: str) -> str:
    def replace_code(match: re.Match[str]) -> str:
        token = match.group(1)
        start = match.start()
        end = match.end()
        if start > 0 and text[start - 1] == "[":
            return match.group(0)
        if end < len(text) and text[end] == "]":
            return match.group(0)
        link = inline_code_link(token)
        if not link:
            return match.group(0)
        return f"[`{token}`]({link})"

    return re.sub(r"`([^`\n]+)`", replace_code, text)


def enhance_markdown(text: str, page: Page) -> str:
    text = convert_doxygen_heading_ids(text)
    text = add_missing_fence_languages(text, page)
    parts = re.split(r"(^```.*?^```[ \t]*$)", text, flags=re.MULTILINE | re.DOTALL)
    for index, part in enumerate(parts):
        if not part.startswith("```"):
            parts[index] = link_inline_code_tokens(part)
    return "".join(parts)


def ensure_title(text: str, title: str) -> str:
    if re.match(r"^#\s+", text):
        return text
    return f"# {title}\n\n{text.lstrip()}"


def roff_to_markdown(source: Path, command_name: str) -> str:
    text = source.read_text(encoding="utf-8", errors="replace")
    lines = [GENERATED_NOTICE.rstrip(), f"# `{command_name}` manual", "", "```roff"]
    lines.extend(text.rstrip().splitlines())
    lines.extend(["```", ""])
    return "\n".join(lines)


def write_page(page: Page, out_dir: Path, source_map: dict[Path, str], repo_url: str) -> None:
    source = REPO_ROOT / page.source
    if not source.exists():
        raise FileNotFoundError(source)
    text = source.read_text(encoding="utf-8")
    text = ensure_title(text, page.title)
    text = rewrite_markdown_links(text, page.source, source_map, repo_url)
    text = enhance_markdown(text, page)
    text = GENERATED_NOTICE + text.rstrip() + "\n"
    (out_dir / f"{page.wiki_name}.md").write_text(text, encoding="utf-8")


def write_sidebar(out_dir: Path, pages: list[Page], manpage_names: list[str]) -> None:
    by_group: dict[str, list[Page]] = {}
    for page in pages:
        by_group.setdefault(page.group, []).append(page)

    lines = [GENERATED_NOTICE.rstrip(), "# MLang Wiki", ""]
    group_order = [
        "Start Here",
        "Language",
        "Standard Library",
        "Math and Audio",
        "DSP Library",
        "Stdlib Modules",
        "Tooling",
        "Examples",
        "Demos",
    ]
    for group in group_order:
        group_pages = by_group.get(group, [])
        if not group_pages:
            continue
        lines.extend([f"## {group}"])
        for page in group_pages:
            lines.append(f"- [[{page.title}|{page.wiki_name}]]")
        lines.append("")

    if manpage_names:
        lines.extend(["## Man Pages"])
        for command_name in manpage_names:
            wiki_name = f"Man-{slugify_wiki_name(command_name)}"
            lines.append(f"- [[`{command_name}`|{wiki_name}]]")
        lines.append("")

    (out_dir / "_Sidebar.md").write_text("\n".join(lines), encoding="utf-8")


def generated_filenames(pages: list[Page]) -> set[str]:
    names = {f"{page.wiki_name}.md" for page in pages}
    names.add("_Sidebar.md")
    for _source, command_name in MANPAGES:
        names.add(f"Man-{slugify_wiki_name(command_name)}.md")
    for module, _filename in STDLIB_MODULE_DOCS:
        names.add(f"{old_stdlib_module_wiki_name(module)}.md")
    return names


def clean_output_dir(out_dir: Path, pages: list[Page]) -> None:
    if not out_dir.exists():
        return
    if (out_dir / ".git").exists():
        for filename in generated_filenames(pages):
            path = out_dir / filename
            if path.exists() and path.is_file():
                path.unlink()
        return
    shutil.rmtree(out_dir)


def validate_demo_directory_coverage() -> None:
    demos_root = REPO_ROOT / "examples"
    index_path = REPO_ROOT / DEMO_INDEX_SOURCE
    documented = set(
        re.findall(
            r"examples/([A-Za-z0-9_.-]+)",
            index_path.read_text(encoding="utf-8"),
        )
    )
    directories = {
        path.name
        for path in demos_root.iterdir()
        if path.is_dir() and not path.name.startswith(".")
    }
    missing = sorted(directories - documented)
    if missing:
        names = ", ".join(f"examples/{name}" for name in missing)
        raise RuntimeError(
            f"Directory demos missing from {DEMO_INDEX_SOURCE}: {names}"
        )


def generate(out_dir: Path, repo_url: str, clean: bool) -> None:
    validate_demo_directory_coverage()
    pages = [page for page in PAGES if (REPO_ROOT / page.source).exists()]
    source_map = build_source_map(pages)

    if clean and out_dir.exists():
        clean_output_dir(out_dir, pages)
    out_dir.mkdir(parents=True, exist_ok=True)

    for page in pages:
        write_page(page, out_dir, source_map, repo_url.rstrip("/"))

    manpage_names: list[str] = []
    for source, command_name in MANPAGES:
        full_source = REPO_ROOT / source
        if not full_source.exists():
            continue
        wiki_name = f"Man-{slugify_wiki_name(command_name)}"
        (out_dir / f"{wiki_name}.md").write_text(
            roff_to_markdown(full_source, command_name), encoding="utf-8"
        )
        manpage_names.append(command_name)

    write_sidebar(out_dir, pages, manpage_names)


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate GitHub Wiki markdown pages from MLang documentation."
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help=f"output directory, default: {DEFAULT_OUTPUT}",
    )
    parser.add_argument(
        "--repo-url",
        default=DEFAULT_REPO_URL,
        help=f"repository URL used for links to source files, default: {DEFAULT_REPO_URL}",
    )
    parser.add_argument(
        "--no-clean",
        action="store_true",
        help="do not delete the output directory before generation",
    )
    args = parser.parse_args()

    out_dir = args.output if args.output.is_absolute() else REPO_ROOT / args.output
    generate(out_dir, args.repo_url, clean=not args.no_clean)
    print(f"Generated GitHub Wiki pages in: {out_dir}")
    print("Rerun this script after editing the source docs to refresh the wiki pages.")
    print("Commit this directory to keep the wiki source in the repository.")
    print("To publish to GitHub Wiki, rerun with --output pointing at a mlang.wiki clone.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
