#include <algorithm>
#include <cctype>
#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <map>
#include <sstream>
#include <string>
#include <thread>
#include <vector>

#ifndef MLANG_SOURCE_DIR
#define MLANG_SOURCE_DIR "."
#endif

namespace fs = std::filesystem;

namespace
{
struct Config
{
    fs::path sourceDir = fs::absolute(fs::path(MLANG_SOURCE_DIR));
    fs::path buildDir = sourceDir / "build";
    std::string buildType = "Release";
    std::string installPrefix = "~/.local";
    std::string binDir = "~/.local/bin";
    std::string jobs;
    bool runUnitTests = false;
    bool runRobotTests = false;
};

std::string trim(std::string s)
{
    auto notSpace = [](unsigned char c) { return !std::isspace(c); };
    s.erase(s.begin(), std::find_if(s.begin(), s.end(), notSpace));
    s.erase(std::find_if(s.rbegin(), s.rend(), notSpace).base(), s.end());
    return s;
}

std::string default_jobs()
{
    unsigned n = std::thread::hardware_concurrency();
    return std::to_string(n == 0 ? 4 : n);
}

bool truthy(const std::string& value)
{
    std::string v = value;
    std::transform(v.begin(), v.end(), v.begin(),
                   [](unsigned char c) { return std::tolower(c); });
    return v == "1" || v == "on" || v == "true" || v == "yes";
}

fs::path config_path(const Config& cfg)
{
    return cfg.buildDir / "mlang-config.conf";
}

fs::path cache_path(const Config& cfg)
{
    return cfg.buildDir / "mlang_config_cache.cmake";
}

std::map<std::string, std::string> read_key_values(const fs::path& path)
{
    std::map<std::string, std::string> out;
    std::ifstream in(path);
    std::string line;
    while(std::getline(in, line))
    {
        line = trim(line);
        if(line.empty() || line[0] == '#')
            continue;
        auto eq = line.find('=');
        if(eq == std::string::npos)
            continue;
        out[trim(line.substr(0, eq))] = trim(line.substr(eq + 1));
    }
    return out;
}

void load_config(Config& cfg, const fs::path& path)
{
    auto kv = read_key_values(path);
    if(kv.count("build_dir"))
        cfg.buildDir = kv["build_dir"];
    if(kv.count("build_type"))
        cfg.buildType = kv["build_type"];
    if(kv.count("install_prefix"))
        cfg.installPrefix = kv["install_prefix"];
    if(kv.count("bin_dir"))
        cfg.binDir = kv["bin_dir"];
    if(kv.count("jobs"))
        cfg.jobs = kv["jobs"];
    if(kv.count("run_unit_tests"))
        cfg.runUnitTests = truthy(kv["run_unit_tests"]);
    if(kv.count("run_robot_tests"))
        cfg.runRobotTests = truthy(kv["run_robot_tests"]);
}

void save_config(const Config& cfg)
{
    fs::create_directories(cfg.buildDir);
    {
        std::ofstream out(config_path(cfg));
        out << "# Generated by mlang-config.\n";
        out << "build_dir=" << cfg.buildDir.string() << "\n";
        out << "build_type=" << cfg.buildType << "\n";
        out << "install_prefix=" << cfg.installPrefix << "\n";
        out << "bin_dir=" << cfg.binDir << "\n";
        out << "jobs=" << cfg.jobs << "\n";
        out << "run_unit_tests=" << (cfg.runUnitTests ? "ON" : "OFF") << "\n";
        out << "run_robot_tests=" << (cfg.runRobotTests ? "ON" : "OFF")
            << "\n";
    }
    {
        std::ofstream out(cache_path(cfg));
        out << "# Generated by mlang-config.\n";
        out << "set(CMAKE_BUILD_TYPE \"" << cfg.buildType
            << "\" CACHE STRING \"\" FORCE)\n";
        out << "set(BUILD_TESTS " << (cfg.runUnitTests ? "ON" : "OFF")
            << " CACHE BOOL \"\" FORCE)\n";
        out << "set(CMAKE_INSTALL_PREFIX \"" << cfg.installPrefix
            << "\" CACHE PATH \"\" FORCE)\n";
    }
}

std::string prompt(const std::string& label, const std::string& current)
{
    std::cout << label << " [" << current << "]: ";
    std::string line;
    std::getline(std::cin, line);
    line = trim(line);
    return line.empty() ? current : line;
}

void print_summary(const Config& cfg)
{
    std::cout << "\nMLang configuration\n";
    std::cout << "  build dir       " << cfg.buildDir.string() << "\n";
    std::cout << "  build type      " << cfg.buildType << "\n";
    std::cout << "  install prefix  " << cfg.installPrefix << "\n";
    std::cout << "  bin dir         " << cfg.binDir << "\n";
    std::cout << "  jobs            " << cfg.jobs << "\n";
    std::cout << "  unit tests      " << (cfg.runUnitTests ? "ON" : "OFF")
              << "\n";
    std::cout << "  Robot tests     " << (cfg.runRobotTests ? "ON" : "OFF")
              << "\n";
    std::cout << "\nLanguage features are always enabled.\n";
}

void choose_build_type(Config& cfg)
{
    const std::vector<std::string> values = {"Release", "Debug",
                                             "RelWithDebInfo", "MinSizeRel"};
    std::cout << "\nBuild type\n";
    for(size_t i = 0; i < values.size(); ++i)
        std::cout << "  " << (i + 1) << ". " << values[i] << "\n";
    std::cout << "Select [current " << cfg.buildType << "]: ";
    std::string line;
    std::getline(std::cin, line);
    if(line.empty())
        return;
    int idx = std::atoi(line.c_str());
    if(idx >= 1 && static_cast<size_t>(idx) <= values.size())
        cfg.buildType = values[static_cast<size_t>(idx - 1)];
}

void run_menu(Config& cfg)
{
    for(;;)
    {
        print_summary(cfg);
        std::cout << "\nMenu\n";
        std::cout << "  1. Edit build directory\n";
        std::cout << "  2. Select build type\n";
        std::cout << "  3. Edit install prefix\n";
        std::cout << "  4. Edit binary install directory\n";
        std::cout << "  5. Edit parallel jobs\n";
        std::cout << "  6. Toggle unit tests\n";
        std::cout << "  7. Toggle Robot tests\n";
        std::cout << "  s. Save and exit\n";
        std::cout << "  q. Quit without saving\n";
        std::cout << "> ";

        std::string choice;
        std::getline(std::cin, choice);
        if(choice == "1")
            cfg.buildDir = prompt("Build directory", cfg.buildDir.string());
        else if(choice == "2")
            choose_build_type(cfg);
        else if(choice == "3")
            cfg.installPrefix = prompt("Install prefix", cfg.installPrefix);
        else if(choice == "4")
            cfg.binDir = prompt("Binary install directory", cfg.binDir);
        else if(choice == "5")
            cfg.jobs = prompt("Parallel jobs", cfg.jobs);
        else if(choice == "6")
            cfg.runUnitTests = !cfg.runUnitTests;
        else if(choice == "7")
            cfg.runRobotTests = !cfg.runRobotTests;
        else if(choice == "s" || choice == "S")
        {
            save_config(cfg);
            std::cout << "Wrote " << config_path(cfg) << "\n";
            std::cout << "Wrote " << cache_path(cfg) << "\n";
            return;
        }
        else if(choice == "q" || choice == "Q")
            return;
    }
}

void print_help(const char* argv0)
{
    std::cout << "Usage: " << argv0 << " [options]\n"
              << "  --build-dir DIR       Build directory\n"
              << "  --build-type TYPE     Release, Debug, RelWithDebInfo, MinSizeRel\n"
              << "  --install-prefix DIR  Install prefix, default ~/.local\n"
              << "  --bin-dir DIR         Binary install directory, default ~/.local/bin\n"
              << "  --jobs N              Parallel build jobs\n"
              << "  --unit-tests on|off   Save unit-test preference, default off\n"
              << "  --robot-tests on|off  Save Robot-test preference, default off\n"
              << "  --write               Write config without opening the menu\n"
              << "  --print               Print current config and exit\n";
}
}

int main(int argc, char** argv)
{
    Config cfg;
    cfg.jobs = default_jobs();

    fs::path importPath;
    bool writeOnly = false;
    bool printOnly = false;

    for(int i = 1; i < argc; ++i)
    {
        std::string arg = argv[i];
        auto needValue = [&](const std::string& name) -> std::string {
            if(i + 1 >= argc)
            {
                std::cerr << name << " requires a value\n";
                std::exit(2);
            }
            return argv[++i];
        };
        if(arg == "--help" || arg == "-h")
        {
            print_help(argv[0]);
            return 0;
        }
        else if(arg == "--build-dir")
            cfg.buildDir = needValue(arg);
        else if(arg == "--build-type")
            cfg.buildType = needValue(arg);
        else if(arg == "--install-prefix")
            cfg.installPrefix = needValue(arg);
        else if(arg == "--bin-dir")
            cfg.binDir = needValue(arg);
        else if(arg == "--jobs")
            cfg.jobs = needValue(arg);
        else if(arg == "--unit-tests")
            cfg.runUnitTests = truthy(needValue(arg));
        else if(arg == "--robot-tests")
            cfg.runRobotTests = truthy(needValue(arg));
        else if(arg == "--import")
            importPath = needValue(arg);
        else if(arg == "--write")
            writeOnly = true;
        else if(arg == "--print")
            printOnly = true;
        else
        {
            std::cerr << "unknown option: " << arg << "\n";
            return 2;
        }
    }

    fs::path defaultConfig = config_path(cfg);
    if(!importPath.empty())
        load_config(cfg, importPath);
    else if(fs::exists(defaultConfig))
        load_config(cfg, defaultConfig);

    for(int i = 1; i < argc; ++i)
    {
        std::string arg = argv[i];
        auto needValue = [&](const std::string&) -> std::string {
            return (i + 1 < argc) ? argv[++i] : std::string();
        };
        if(arg == "--build-dir")
            cfg.buildDir = needValue(arg);
        else if(arg == "--build-type")
            cfg.buildType = needValue(arg);
        else if(arg == "--install-prefix")
            cfg.installPrefix = needValue(arg);
        else if(arg == "--bin-dir")
            cfg.binDir = needValue(arg);
        else if(arg == "--jobs")
            cfg.jobs = needValue(arg);
        else if(arg == "--unit-tests")
            cfg.runUnitTests = truthy(needValue(arg));
        else if(arg == "--robot-tests")
            cfg.runRobotTests = truthy(needValue(arg));
        else if(arg == "--import")
            (void)needValue(arg);
    }

    if(printOnly)
    {
        print_summary(cfg);
        return 0;
    }
    if(writeOnly)
    {
        save_config(cfg);
        std::cout << "Wrote " << config_path(cfg) << "\n";
        std::cout << "Wrote " << cache_path(cfg) << "\n";
        return 0;
    }

    run_menu(cfg);
    return 0;
}
