#include <iostream>
#include <llvm/IR/LLVMContext.h>
#include <llvm/IR/Module.h>
#include <llvm/IR/IRBuilder.h>

// Declare functions generated by Flex and Bison
extern int yyparse();
extern FILE* yyin;

// Global variables
llvm::LLVMContext TheContext;
llvm::IRBuilder<> Builder(TheContext);
std::unique_ptr<llvm::Module> TheModule;

int main(int argc, char** argv) {
    if (argc != 2) {
        std::cerr << "Usage: " << argv[0] << " <input_file>" << std::endl;
        return 1;
    }

    FILE* input_file = fopen(argv[1], "r");
    if (!input_file) {
        std::cerr << "Error opening file: " << argv[1] << std::endl;
        return 1;
    }

    yyin = input_file;

    TheModule = std::make_unique<llvm::Module>("MyLanguage", TheContext);

    if (yyparse() == 0) {
        std::cout << "Parsing completed successfully." << std::endl;
        // Here you would typically walk the AST and generate LLVM IR
        TheModule->print(llvm::errs(), nullptr);
    } else {
        std::cerr << "Parsing failed." << std::endl;
        return 1;
    }

    fclose(input_file);
    return 0;
}
